"""Single source of truth for version/model info shown in the app and About page."""
APP_VERSION = "0.5.1"
MODEL_NAME = "sherpa-onnx-streaming-zipformer-en-2023-06-26"
MODEL_SOURCE_URL = "https://github.com/k2-fsa/sherpa-onnx"
ASR_ENGINE = "Sherpa-ONNX (k2-fsa)"
